{{- if .Values.jupyter.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "dask.fullname" . }}-jupyter
  labels:
    app: {{ template "dask.fullname" . }}-jupyter
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.jupyter.ingress.annotations | indent 4 }}
spec:
  tls:
  - hosts:
    - {{ .Values.jupyter.ingress.hostname }}
    secretName: {{ template "dask.fullname" . }}-jupyter
  rules:
    - host: {{ .Values.jupyter.ingress.hostname }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ template "dask.fullname" . }}-jupyter
                port:
                  number: {{ .Values.jupyter.servicePort }}
{{- end -}}
